// @ts-nocheck
// Auto-generated by tauri-specta. DO NOT EDIT.


// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * Saves emergency data to a JSON file for later recovery.
 * Uses an atomic write (temp file → rename) so a crash mid-write never corrupts existing data.
 * Enforces a 10 MB size limit.
 */
async saveEmergencyData(filename: string, data: JsonValue) : Promise<Result<null, RecoveryError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_emergency_data", { filename, data }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Loads emergency data from a previously saved JSON file.
 * Returns `RecoveryError::FileNotFound` if the file does not exist.
 */
async loadEmergencyData(filename: string) : Promise<Result<JsonValue, RecoveryError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_emergency_data", { filename }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Removes recovery files older than 7 days. Returns the count of removed files.
 */
async cleanupOldRecoveryFiles() : Promise<Result<number, RecoveryError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cleanup_old_recovery_files") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Checks GitHub releases for a version newer than the running app.
 * 
 * Returns `UpdateError::NoUpdateAvailable` when already up to date.
 */
async checkForUpdate() : Promise<Result<UpdateInfo, UpdateError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_for_update") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Downloads the installer from `url`, verifies its SHA-256 against `expected_checksum`,
 * then launches it and exits the app.
 * 
 * This command never returns `Ok(())` — it calls `std::process::exit(0)` on success.
 */
async downloadAndInstallUpdate(url: string, expectedChecksum: string) : Promise<Result<null, UpdateError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("download_and_install_update", { url, expectedChecksum }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Returns the unified diff.
 * 
 * - `ref1 = None, ref2 = None` → HEAD vs working directory (includes staged)
 * - `ref1 = Some("HEAD~1"), ref2 = Some("HEAD")` → diff between two commits
 */
async gitDiff(repoPath: string, ref1: string | null, ref2: string | null) : Promise<Result<GitDiff, GitError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("git_diff", { repoPath, ref1, ref2 }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Returns the working-tree status (tracked + untracked files).
 */
async gitStatus(repoPath: string) : Promise<Result<GitStatusEntry[], GitError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("git_status", { repoPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Returns how many commits the local branch is ahead of and behind its upstream.
 * Returns `ahead = 0, behind = 0` when there is no upstream configured.
 */
async gitAheadBehind(repoPath: string, branch: string) : Promise<Result<GitAheadBehind, GitError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("git_ahead_behind", { repoPath, branch }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Returns the name of the currently checked-out branch.
 * Returns `GitError::DetachedHead` when in detached HEAD state.
 */
async gitCurrentBranch(repoPath: string) : Promise<Result<string, GitError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("git_current_branch", { repoPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Shows the quick pane, positioning it on the monitor that contains the cursor.
 */
async showQuickPane() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("show_quick_pane") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Dismisses the quick pane.
 * On macOS, resigns key window status before hiding to avoid activating the main window.
 */
async dismissQuickPane() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("dismiss_quick_pane") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Toggles the quick pane visibility.
 */
async toggleQuickPane() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("toggle_quick_pane") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Returns the compiled-in default shortcut string.
 */
async getDefaultQuickPaneShortcut() : Promise<string> {
    return await TAURI_INVOKE("get_default_quick_pane_shortcut");
},
/**
 * Updates the global shortcut used to summon the quick pane.
 * Pass `None` to reset to the default shortcut.
 */
async updateQuickPaneShortcut(shortcut: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_quick_pane_shortcut", { shortcut }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Enables or disables the quick pane by registering/unregistering its global shortcut.
 */
async setQuickPaneEnabled(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_quick_pane_enabled", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Set the zoom factor for a webview window (default: `"main"`).
 */
async setZoom(windowLabel: string | null, factor: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_zoom", { windowLabel, factor }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get the current zoom factor for a webview window (default: `"main"`).
 * Returns the last value set via `set_zoom`, or `1.0` if never zoomed.
 */
async getZoom(windowLabel: string | null) : Promise<number> {
    return await TAURI_INVOKE("get_zoom", { windowLabel });
},
/**
 * Set the same zoom factor on every open webview window.
 */
async broadcastZoom(factor: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("broadcast_zoom", { factor }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Set the taskbar / dock progress bar on the main window.
 * 
 * `progress` — a value in `0..=100`; pass `None` to clear the indicator.
 */
async setProgressBar(progress: number | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_progress_bar", { progress }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get the outer position and size of a window (default: `"main"`).
 */
async getWindowBounds(windowLabel: string | null) : Promise<Result<WindowBounds, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_window_bounds", { windowLabel }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Set the outer position and size of a window (default: `"main"`).
 */
async setWindowBounds(windowLabel: string | null, bounds: WindowBounds) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_window_bounds", { windowLabel, bounds }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Returns `true` when running inside Windows Subsystem for Linux.
 * 
 * Checks `WSL_DISTRO_NAME` env var first (reliable since WSL 2), then
 * falls back to reading `/proc/version` for WSL 1 hosts.
 */
async isWsl() : Promise<boolean> {
    return await TAURI_INVOKE("is_wsl");
},
/**
 * Returns true if WSL is available on this system (Windows only).
 */
async wslIsAvailable() : Promise<boolean> {
    return await TAURI_INVOKE("wsl_is_available");
},
/**
 * Lists installed WSL distributions (Windows only; empty list on other platforms).
 */
async wslListDistros() : Promise<Result<WslDistro[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("wsl_list_distros") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Executes a shell command inside a WSL distro (Windows only).
 */
async wslExecute(distro: string, command: string, cwd: string | null) : Promise<Result<WslOutput, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("wsl_execute", { distro, command, cwd }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Returns the current sandbox status for Claude CLI child processes.
 * On Linux: detects whether `bwrap` (bubblewrap) is available and active.
 * On macOS / Windows: always returns unavailable/inactive.
 */
async sandboxStatus() : Promise<SandboxStatus> {
    return await TAURI_INVOKE("sandbox_status");
},
/**
 * Returns the currently-known ports for sidecars that use port discovery.
 * A `None` entry means the sidecar hasn't announced its port yet.
 */
async getSidecarPorts() : Promise<SidecarPorts> {
    return await TAURI_INVOKE("get_sidecar_ports");
},
async getPreflightSafetyTierReference() : Promise<SafetyTierRef[]> {
    return await TAURI_INVOKE("get_preflight_safety_tier_reference");
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type GitAheadBehind = { ahead: number; behind: number }
export type GitDiff = { stat: string; diff: string; files_changed: number; insertions: number; deletions: number }
export type GitError = { type: "NotFound"; message: string } | { type: "RefNotFound"; message: string } | { type: "DetachedHead" } | { type: "Other"; message: string }
export type GitStatusEntry = { path: string; 
/**
 * "added", "modified", "deleted", "renamed", "untracked", "conflicted"
 */
status: string; staged: boolean }
export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>
export type RecoveryError = { type: "FileNotFound" } | { type: "ValidationError"; message: string } | { type: "DataTooLarge"; max_bytes: number } | { type: "IoError"; message: string } | { type: "ParseError"; message: string }
/**
 * Read-only labels for `featuregraph::preflight::ChangeTier` (governance UI).
 */
export type SafetyTierRef = { id: string; label: string; description: string }
export type SandboxStatus = { 
/**
 * True if a sandboxing method (bwrap) was found on PATH.
 */
available: boolean; 
/**
 * True if sandboxing is actively wrapping spawned CLI processes.
 */
active: boolean; 
/**
 * The sandboxing method in use, e.g. "bwrap". None when inactive.
 */
method: string | null }
export type SidecarPorts = { axiomregent: number | null }
export type UpdateError = { type: "NoUpdateAvailable" } | { type: "NetworkError"; message: string } | { type: "ChecksumMismatch" } | { type: "LaunchFailed"; message: string }
export type UpdateInfo = { 
/**
 * Version string without leading "v" (e.g. "0.2.0").
 */
version: string; 
/**
 * Release notes from the GitHub release body.
 */
notes: string; 
/**
 * Direct download URL for the platform installer asset.
 */
url: string; 
/**
 * Expected SHA-256 hex digest of the installer file.
 */
checksum: string }
export type WindowBounds = { x: number; y: number; width: number; height: number }
export type WslDistro = { name: string; is_default: boolean; state: string }
export type WslOutput = { stdout: string; stderr: string; exit_code: number }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
