// Code generated by the Encore v1.56.5 client generator. DO NOT EDIT.

// Disable eslint, jshint, and jslint for this file.
/* eslint-disable */
/* jshint ignore:start */
/*jslint-disable*/

/**
 * BaseURL is the base URL for calling the Encore application's API.
 */
export type BaseURL = string

export const Local: BaseURL = "http://localhost:4000"

/**
 * Environment returns a BaseURL for calling the cloud environment with the given name.
 */
export function Environment(name: string): BaseURL {
    return `https://${name}-fullstack-app-37a2.encr.app`
}

/**
 * PreviewEnv returns a BaseURL for calling the preview environment with the given PR number.
 */
export function PreviewEnv(pr: number | string): BaseURL {
    return Environment(`pr${pr}`)
}

const BROWSER = typeof globalThis === "object" && ("window" in globalThis);

/**
 * Client is an API client for the fullstack-app-37a2 Encore application.
 */
export default class Client {
    public readonly admin: admin.ServiceClient
    public readonly agents: agents.ServiceClient
    public readonly audit: audit.ServiceClient
    public readonly auth: auth.ServiceClient
    public readonly deploy: deploy.ServiceClient
    public readonly factory: factory.ServiceClient
    public readonly github: github.ServiceClient
    public readonly grants: grants.ServiceClient
    public readonly knowledge: knowledge.ServiceClient
    public readonly monitor: monitor.ServiceClient
    public readonly policy: policy.ServiceClient
    public readonly projects: projects.ServiceClient
    public readonly site: site.ServiceClient
    public readonly sync: sync.ServiceClient
    public readonly workspaces: workspaces.ServiceClient
    public readonly frontend: frontend.ServiceClient
    private readonly options: ClientOptions
    private readonly target: string


    /**
     * Creates a Client for calling the public and authenticated APIs of your Encore application.
     *
     * @param target  The target which the client should be configured to use. See Local and Environment for options.
     * @param options Options for the client
     */
    constructor(target: BaseURL, options?: ClientOptions) {
        this.target = target
        this.options = options ?? {}
        const base = new BaseClient(this.target, this.options)
        this.admin = new admin.ServiceClient(base)
        this.agents = new agents.ServiceClient(base)
        this.audit = new audit.ServiceClient(base)
        this.auth = new auth.ServiceClient(base)
        this.deploy = new deploy.ServiceClient(base)
        this.factory = new factory.ServiceClient(base)
        this.github = new github.ServiceClient(base)
        this.grants = new grants.ServiceClient(base)
        this.knowledge = new knowledge.ServiceClient(base)
        this.monitor = new monitor.ServiceClient(base)
        this.policy = new policy.ServiceClient(base)
        this.projects = new projects.ServiceClient(base)
        this.site = new site.ServiceClient(base)
        this.sync = new sync.ServiceClient(base)
        this.workspaces = new workspaces.ServiceClient(base)
        this.frontend = new frontend.ServiceClient(base)
    }

    /**
     * Creates a new Encore client with the given client options set.
     *
     * @param options Client options to set. They are merged with existing options.
     **/
    public with(options: ClientOptions): Client {
        return new Client(this.target, {
            ...this.options,
            ...options,
        })
    }
}

/**
 * ClientOptions allows you to override any default behaviour within the generated Encore client.
 */
export interface ClientOptions {
    /**
     * By default the client will use the inbuilt fetch function for making the API requests.
     * however you can override it with your own implementation here if you want to run custom
     * code on each API request made or response received.
     */
    fetcher?: Fetcher

    /** Default RequestInit to be used for the client */
    requestInit?: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }

    /**
     * Allows you to set the authentication data to be used for each
     * request either by passing in a static object or by passing in
     * a function which returns a new object for each request.
     */
    auth?: auth.AuthParams | AuthDataGenerator
}

export namespace admin {
    export interface AuditRow {
        id: string
        actorUserId: string
        action: string
        targetType: string
        targetId: string
        metadata: { [key: string]: any }
        createdAt: string
    }

    export interface ListAuditResponse {
        events: AuditRow[]
        nextCursor?: string
    }

    export interface ListUsersResponse {
        users: UserRow[]
    }

    export interface SetRoleResponse {
        ok: true
    }

    export interface SetDisabledResponse {
        ok: true
    }

    export interface UserRow {
        id: string
        email: string
        name: string
        role: "user" | "admin"
        disabled: boolean
        lastLoginAt: string | null
        activeSessionCount: number
        createdAt: string
    }

    export interface SessionRow {
        id: string
        userId: string
        idpProvider: string
        platformRole: string
        orgSlug: string
        expiresAt: string
        createdAt: string
    }

    export interface ListSessionsResponse {
        sessions: SessionRow[]
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.listAudit = this.listAudit.bind(this)
            this.listUsers = this.listUsers.bind(this)
            this.setRole = this.setRole.bind(this)
            this.setDisabled = this.setDisabled.bind(this)
            this.listUserSessions = this.listUserSessions.bind(this)
            this.revokeUserSessions = this.revokeUserSessions.bind(this)
            this.revokeUserSession = this.revokeUserSession.bind(this)
        }

        public async listAudit(params?: {
    cursor?: string
    limit?: number
    action?: string
    actorUserId?: string
    targetType?: string
    targetId?: string
    from?: string
    to?: string
}): Promise<ListAuditResponse> {
            const query = new URLSearchParams()
            if (params) {
                for (const [k, v] of Object.entries(params)) {
                    if (v !== undefined && v !== null) query.set(k, String(v))
                }
            }
            const qs = query.toString()
            const resp = await this.baseClient.callTypedAPI("GET", `/admin/audit${qs ? `?${qs}` : ``}`)
            return await resp.json() as ListAuditResponse
        }

        public async listUsers(): Promise<ListUsersResponse> {
            const resp = await this.baseClient.callTypedAPI("GET", `/admin/users`)
            return await resp.json() as ListUsersResponse
        }

        public async setRole(params: {
    actorUserId?: string
    userId: string
    role: "user" | "admin"
}): Promise<SetRoleResponse> {
            const resp = await this.baseClient.callTypedAPI("POST", `/admin/users/set-role`, JSON.stringify(params))
            return await resp.json() as SetRoleResponse
        }

        public async setDisabled(params: {
    userId: string
    disabled: boolean
}): Promise<SetDisabledResponse> {
            const resp = await this.baseClient.callTypedAPI("POST", `/admin/users/set-disabled`, JSON.stringify(params))
            return await resp.json() as SetDisabledResponse
        }

        public async listUserSessions(params: {
    userId: string
}): Promise<ListSessionsResponse> {
            const resp = await this.baseClient.callTypedAPI("GET", `/admin/users/${params.userId}/sessions`)
            return await resp.json() as ListSessionsResponse
        }

        public async revokeUserSessions(params: {
    userId: string
}): Promise<{ ok: true }> {
            const resp = await this.baseClient.callTypedAPI("DELETE", `/admin/users/${params.userId}/sessions`)
            return await resp.json() as { ok: true }
        }

        public async revokeUserSession(params: {
    userId: string
    tokenId: string
}): Promise<{ ok: true }> {
            const resp = await this.baseClient.callTypedAPI("DELETE", `/admin/users/${params.userId}/sessions/${params.tokenId}`)
            return await resp.json() as { ok: true }
        }
    }
}

export namespace agents {
    export interface AgentAuthorizedResponse {
        authorized: true
    }

    export interface AgentPolicyRow {
        id: string
        orgId: string
        slug: string
        blocked: boolean
        reason: string
        createdAt: string
        updatedAt: string
    }

    export interface DeleteAgentPolicyResponse {
        ok: true
    }

    export interface ListAgentPoliciesResponse {
        policies: AgentPolicyRow[]
    }

    export interface UpsertAgentPolicyRequest {
        slug: string
        blocked: boolean
        reason?: string
        actorUserId?: string
    }

    export interface UpsertAgentPolicyResponse {
        policy: AgentPolicyRow
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.deleteAgentPolicy = this.deleteAgentPolicy.bind(this)
            this.isAgentAuthorized = this.isAgentAuthorized.bind(this)
            this.listAgentPolicies = this.listAgentPolicies.bind(this)
            this.upsertAgentPolicy = this.upsertAgentPolicy.bind(this)
        }

        public async deleteAgentPolicy(id: string): Promise<DeleteAgentPolicyResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("DELETE", `/admin/agent-policies/${encodeURIComponent(id)}`)
            return await resp.json() as DeleteAgentPolicyResponse
        }

        /**
         * Seam D: Validate agent execution against org-level policies.
         * GET /api/agents/:slug/authorized
         * 
         * Returns 200 if the agent is authorized.
         * Returns 403 with { reason } if the agent is blocked.
         * Agents with no policy row are allowed by default.
         */
        public async isAgentAuthorized(slug: string): Promise<AgentAuthorizedResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/api/agents/${encodeURIComponent(slug)}/authorized`)
            return await resp.json() as AgentAuthorizedResponse
        }

        public async listAgentPolicies(): Promise<ListAgentPoliciesResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/admin/agent-policies`)
            return await resp.json() as ListAgentPoliciesResponse
        }

        public async upsertAgentPolicy(params: UpsertAgentPolicyRequest): Promise<UpsertAgentPolicyResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/admin/agent-policies`, JSON.stringify(params))
            return await resp.json() as UpsertAgentPolicyResponse
        }
    }
}

export namespace audit {
    export interface IngestAuditRequest {
        authorization: string
        action: string
        targetType: string
        targetId: string
        metadata?: { [key: string]: any }
    }

    export interface IngestAuditResponse {
        ok: true
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.ingestAuditRecord = this.ingestAuditRecord.bind(this)
        }

        /**
         * Seam B: Ingest audit records from OPC axiomregent.
         * POST /api/audit-records — M2M bearer token auth (OIDC JWT or static fallback).
         */
        public async ingestAuditRecord(params: IngestAuditRequest): Promise<IngestAuditResponse> {
            // Convert our params into the objects we need for the request
            const headers = makeRecord<string, string>({
                authorization: params.authorization,
            })

            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                action:     params.action,
                metadata:   params.metadata,
                targetId:   params.targetId,
                targetType: params.targetType,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/api/audit-records`, JSON.stringify(body), {headers})
            return await resp.json() as IngestAuditResponse
        }
    }
}

export namespace auth {
    export interface AuthParams {
        authorization?: string
        cookie?: string
    }

    export interface AuthSignoutResponse {
        ok: boolean
        setCookie?: string
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.adminSignout = this.adminSignout.bind(this)
            this.getPendingOrgs = this.getPendingOrgs.bind(this)
            this.githubCallback = this.githubCallback.bind(this)
            this.githubLogin = this.githubLogin.bind(this)
            this.orgSelectComplete = this.orgSelectComplete.bind(this)
            this.signout = this.signout.bind(this)
        }

        public async adminSignout(): Promise<AuthSignoutResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/admin/auth/signout`)
            return await resp.json() as AuthSignoutResponse
        }

        public async getPendingOrgs(method: "GET", body?: RequestInit["body"], options?: CallParameters): Promise<globalThis.Response> {
            return this.baseClient.callAPI(method, `/auth/pending-orgs`, body, options)
        }

        public async githubCallback(method: "GET", body?: RequestInit["body"], options?: CallParameters): Promise<globalThis.Response> {
            return this.baseClient.callAPI(method, `/auth/github/callback`, body, options)
        }

        public async githubLogin(method: "GET", body?: RequestInit["body"], options?: CallParameters): Promise<globalThis.Response> {
            return this.baseClient.callAPI(method, `/auth/github`, body, options)
        }

        public async orgSelectComplete(method: "GET", body?: RequestInit["body"], options?: CallParameters): Promise<globalThis.Response> {
            return this.baseClient.callAPI(method, `/auth/org-select/complete`, body, options)
        }

        public async signout(): Promise<AuthSignoutResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/auth/signout`)
            return await resp.json() as AuthSignoutResponse
        }
    }
}

/**
 * Deploy service: proxies deployment requests to deployd-api using OIDC M2M auth.
 * Absorbs the former stagecraft-api functionality.
 */
export namespace deploy {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.createDeployment = this.createDeployment.bind(this)
            this.healthz = this.healthz.bind(this)
        }

        public async createDeployment(method: "POST", body?: RequestInit["body"], options?: CallParameters): Promise<globalThis.Response> {
            return this.baseClient.callAPI(method, `/v1/deployments`, body, options)
        }

        public async healthz(method: "GET", body?: RequestInit["body"], options?: CallParameters): Promise<globalThis.Response> {
            return this.baseClient.callAPI(method, `/healthz`, body, options)
        }
    }
}

export namespace factory {
    export interface AuditEntry {
        id: string
        pipelineId: string
        timestamp: string
        event: string
        actor: string | null
        stageId: string | null
        featureId: string | null
        details: any
    }

    export interface AuditRequest {
        workspaceId: string
        from?: string
        limit?: number
    }

    export interface AuditResponse {
        entries: AuditEntry[]
        total: number
    }

    export interface BusinessDocRef {
        name: string
        "storage_ref": string
    }

    export interface CancelRequest {
        reason: string
        actorUserId: string
        workspaceId: string
    }

    export interface CancelResponse {
        "pipeline_id": string
        "cancelled_at": string
        "audit_entry_id": string
    }

    export interface ConfirmRequest {
        notes?: string
        actorUserId: string
        workspaceId: string
    }

    export interface ConfirmResponse {
        stage: string
        "confirmed_by": string
        "confirmed_at": string
        "audit_entry_id": string
    }

    export interface DeployRequest {
        environment: string
        "git_ref": string
        "registry_image"?: string
        actorUserId: string
        workspaceId: string
    }

    export interface DeployResponse {
        "deployment_id": string
        target: string
        status: string
    }

    export interface EventIngestionRequest {
        "pipeline_id": string
        events: OrchestratorEvent[]
        workspaceId: string
    }

    export interface EventIngestionResponse {
        ingested: number
    }

    export interface InitRequest {
        adapter: string
        "business_docs"?: BusinessDocRef[]
        "knowledge_object_ids"?: string[]
        "policy_overrides"?: PolicyOverrides
        actorUserId: string
        workspaceId: string
    }

    export interface InitResponse {
        "pipeline_id": string
        adapter: string
        "policy_bundle_id": string
        status: string
        "created_at": string
    }

    export interface LookupArtifactsRequest {
        "content_hash": string
        "stage_id": string
        workspaceId: string
    }

    export interface LookupArtifactsResponse {
        found: boolean
        artifact: {
            "pipeline_id": string
            "stage_id": string
            "artifact_type": string
            "content_hash": string
            "storage_path": string
            "size_bytes": number
            "created_at": string
        } | null
    }

    export interface OrchestratorEvent {
        "event_type": string
        "step_id"?: string
        timestamp: string
        payload?: { [key: string]: any }
    }

    export interface PolicyOverrides {
        "max_retry_per_feature"?: number
        "token_budget_total"?: number
    }

    export interface PromotionRequest {
        workflowId: string
        pipelineId: string
        promotedBy?: string
    }

    export interface PromotionResult {
        eligible: boolean
        promotionId?: string
        missingRecords: string[]
    }

    export interface RecordArtifactsRequest {
        "pipeline_id": string
        "stage_id": string
        artifacts: {
            "artifact_type": string
            "content_hash": string
            "storage_path": string
            "size_bytes": number
        }[]
        workspaceId: string
    }

    export interface RecordArtifactsResponse {
        recorded: number
    }

    export interface RejectRequest {
        feedback: string
        actorUserId: string
        workspaceId: string
    }

    export interface RejectResponse {
        stage: string
        "rejected_by": string
        "rejected_at": string
        feedback: string
        "audit_entry_id": string
    }

    export interface ScaffoldFeatureReport {
        "feature_id": string
        category: "data" | "api" | "ui" | "configure" | "trim" | "validate"
        status: "pending" | "in_progress" | "completed" | "failed"
        "retry_count"?: number
        "last_error"?: string
        "files_created"?: string[]
        "prompt_tokens"?: number
        "completion_tokens"?: number
    }

    export interface ScaffoldProgressRequest {
        "pipeline_id": string
        features: ScaffoldFeatureReport[]
        actorUserId: string
        workspaceId: string
    }

    export interface ScaffoldProgressResponse {
        upserted: number
        "audit_entry_id": string
    }

    export interface StatusResponse {
        "pipeline_id": string
        status: string
        adapter: string
        "current_stage": string | null
        stages: { [key: string]: {
            status: string
            "started_at"?: string
            "completed_at"?: string
            "confirmed_by"?: string
            "confirmed_at"?: string
        } }
        "policy_bundle": any | null
        "token_spend": {
            total: number
            budget: number
            "by_stage": { [key: string]: number }
        }
        "started_at": string | null
    }

    export interface StatusUpdateRequest {
        "pipeline_id": string
        status: "running" | "paused" | "completed" | "failed"
        "current_stage"?: string
        error?: string
        phase?: "process" | "scaffold"
        actorUserId: string
        workspaceId: string
    }

    export interface StatusUpdateResponse {
        "pipeline_id": string
        status: string
        "audit_entry_id": string
    }

    export interface TokenSpendRequest {
        "run_id": string
        "stage_id": string
        "prompt_tokens": number
        "completion_tokens": number
        model: string
        workspaceId: string
    }

    export interface WorkspaceLookupArtifactRequest {
        "content_hash": string
        workspaceId: string
    }

    export interface WorkspaceLookupArtifactResponse {
        found: boolean
        artifacts: {
            "workflow_id": string
            "step_id": string
            filename: string
            "content_hash": string
            "size_bytes": number
            "producer_agent": string | null
            "created_at": string
        }[]
    }

    export interface WorkspaceRecordArtifactRequest {
        "content_hash": string
        filename: string
        "step_id": string
        "workflow_id": string
        "size_bytes": number
        "content_type"?: string
        "producer_agent"?: string
        workspaceId: string
    }

    export interface WorkspaceRecordArtifactResponse {
        recorded: boolean
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.cancelPipeline = this.cancelPipeline.bind(this)
            this.confirmStage = this.confirmStage.bind(this)
            this.createPromotion = this.createPromotion.bind(this)
            this.getAudit = this.getAudit.bind(this)
            this.getStatus = this.getStatus.bind(this)
            this.ingestEvents = this.ingestEvents.bind(this)
            this.initPipeline = this.initPipeline.bind(this)
            this.lookupArtifact = this.lookupArtifact.bind(this)
            this.recordArtifacts = this.recordArtifacts.bind(this)
            this.rejectStage = this.rejectStage.bind(this)
            this.reportScaffoldProgress = this.reportScaffoldProgress.bind(this)
            this.reportTokenSpend = this.reportTokenSpend.bind(this)
            this.triggerDeploy = this.triggerDeploy.bind(this)
            this.updatePipelineStatus = this.updatePipelineStatus.bind(this)
            this.workspaceLookupArtifact = this.workspaceLookupArtifact.bind(this)
            this.workspaceRecordArtifact = this.workspaceRecordArtifact.bind(this)
        }

        public async cancelPipeline(id: string, params: CancelRequest): Promise<CancelResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/api/projects/${encodeURIComponent(id)}/factory/cancel`, JSON.stringify(params))
            return await resp.json() as CancelResponse
        }

        public async confirmStage(id: string, stageId: string, params: ConfirmRequest): Promise<ConfirmResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/api/projects/${encodeURIComponent(id)}/factory/stage/${encodeURIComponent(stageId)}/confirm`, JSON.stringify(params))
            return await resp.json() as ConfirmResponse
        }

        /**
         * Validate a completed pipeline run for promotion eligibility.
         * 
         * Checks that the pipeline belongs to the workspace, all stages have records,
         * artifacts are present, and the audit log has a completion event. If all checks
         * pass, creates a promotion record.
         * 
         * Spec 097 Slice 3.
         */
        public async createPromotion(workspace_id: string, params: PromotionRequest): Promise<PromotionResult> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/api/workspaces/${encodeURIComponent(workspace_id)}/promotions`, JSON.stringify(params))
            return await resp.json() as PromotionResult
        }

        public async getAudit(id: string, params: AuditRequest): Promise<AuditResponse> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                from:        params.from,
                limit:       params.limit === undefined ? undefined : String(params.limit),
                workspaceId: params.workspaceId,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/api/projects/${encodeURIComponent(id)}/factory/audit`, undefined, {query})
            return await resp.json() as AuditResponse
        }

        public async getStatus(id: string, params: {
    workspaceId: string
}): Promise<StatusResponse> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                workspaceId: params.workspaceId,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/api/projects/${encodeURIComponent(id)}/factory/status`, undefined, {query})
            return await resp.json() as StatusResponse
        }

        public async ingestEvents(id: string, params: EventIngestionRequest): Promise<EventIngestionResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/api/projects/${encodeURIComponent(id)}/factory/events`, JSON.stringify(params))
            return await resp.json() as EventIngestionResponse
        }

        public async initPipeline(id: string, params: InitRequest): Promise<InitResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/api/projects/${encodeURIComponent(id)}/factory/init`, JSON.stringify(params))
            return await resp.json() as InitResponse
        }

        public async lookupArtifact(id: string, params: LookupArtifactsRequest): Promise<LookupArtifactsResponse> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                "content_hash": params["content_hash"],
                "stage_id":     params["stage_id"],
                workspaceId:    params.workspaceId,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/api/projects/${encodeURIComponent(id)}/factory/artifacts/lookup`, undefined, {query})
            return await resp.json() as LookupArtifactsResponse
        }

        public async recordArtifacts(id: string, params: RecordArtifactsRequest): Promise<RecordArtifactsResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/api/projects/${encodeURIComponent(id)}/factory/artifacts`, JSON.stringify(params))
            return await resp.json() as RecordArtifactsResponse
        }

        public async rejectStage(id: string, stageId: string, params: RejectRequest): Promise<RejectResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/api/projects/${encodeURIComponent(id)}/factory/stage/${encodeURIComponent(stageId)}/reject`, JSON.stringify(params))
            return await resp.json() as RejectResponse
        }

        public async reportScaffoldProgress(id: string, params: ScaffoldProgressRequest): Promise<ScaffoldProgressResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/api/projects/${encodeURIComponent(id)}/factory/scaffold-progress`, JSON.stringify(params))
            return await resp.json() as ScaffoldProgressResponse
        }

        public async reportTokenSpend(id: string, params: TokenSpendRequest): Promise<void> {
            await this.baseClient.callTypedAPI("POST", `/api/projects/${encodeURIComponent(id)}/factory/token-spend`, JSON.stringify(params))
        }

        public async triggerDeploy(id: string, params: DeployRequest): Promise<DeployResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/api/projects/${encodeURIComponent(id)}/factory/deploy`, JSON.stringify(params))
            return await resp.json() as DeployResponse
        }

        public async updatePipelineStatus(id: string, params: StatusUpdateRequest): Promise<StatusUpdateResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/api/projects/${encodeURIComponent(id)}/factory/status-update`, JSON.stringify(params))
            return await resp.json() as StatusUpdateResponse
        }

        public async workspaceLookupArtifact(workspace_id: string, params: WorkspaceLookupArtifactRequest): Promise<WorkspaceLookupArtifactResponse> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                "content_hash": params["content_hash"],
                workspaceId:    params.workspaceId,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/api/workspaces/${encodeURIComponent(workspace_id)}/artifacts`, undefined, {query})
            return await resp.json() as WorkspaceLookupArtifactResponse
        }

        public async workspaceRecordArtifact(workspace_id: string, params: WorkspaceRecordArtifactRequest): Promise<WorkspaceRecordArtifactResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/api/workspaces/${encodeURIComponent(workspace_id)}/artifacts`, JSON.stringify(params))
            return await resp.json() as WorkspaceRecordArtifactResponse
        }
    }
}

export namespace github {
    export interface TokenRequest {
        repo: string
        scope: string
    }

    export interface TokenResponse {
        token: string
        "expires_at": string
        permissions: { [key: string]: string }
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.getToken = this.getToken.bind(this)
            this.handleWebhook = this.handleWebhook.bind(this)
        }

        /**
         * POST /api/github/token — broker a scoped installation token
         */
        public async getToken(params: TokenRequest): Promise<TokenResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/api/github/token`, JSON.stringify(params))
            return await resp.json() as TokenResponse
        }

        /**
         * POST /api/github/webhook — receive GitHub webhook events
         */
        public async handleWebhook(method: "POST", body?: RequestInit["body"], options?: CallParameters): Promise<globalThis.Response> {
            return this.baseClient.callAPI(method, `/api/github/webhook`, body, options)
        }
    }
}

export namespace grants {
    export interface GrantsRequest {
        authorization: string
    }

    export interface GrantsResponse {
        "enable_file_read": boolean
        "enable_file_write": boolean
        "enable_network": boolean
        "max_tier": number
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.getGrants = this.getGrants.bind(this)
        }

        /**
         * Seam C: Serve workspace-scoped permission grants to OPC desktop app.
         * GET /api/grants/:userId/:workspaceId — M2M bearer token auth (OIDC JWT or static fallback).
         * 
         * Returns the grant row if found, otherwise returns sensible defaults (read-only, tier 1).
         */
        public async getGrants(userId: string, workspaceId: string, params: GrantsRequest): Promise<GrantsResponse> {
            // Convert our params into the objects we need for the request
            const headers = makeRecord<string, string>({
                authorization: params.authorization,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/api/grants/${encodeURIComponent(userId)}/${encodeURIComponent(workspaceId)}`, undefined, {headers})
            return await resp.json() as GrantsResponse
        }
    }
}

export namespace knowledge {
    export interface BindRequest {
        knowledgeObjectIds: string[]
    }

    export interface CreateConnectorRequest {
        type: string
        name: string
        config?: { [key: string]: any }
        syncSchedule?: string
    }

    export interface DocumentBindingRow {
        id: string
        projectId: string
        knowledgeObjectId: string
        boundBy: string
        boundAt: string
    }

    export interface KnowledgeObjectRow {
        id: string
        workspaceId: string
        connectorId: string | null
        storageKey: string
        filename: string
        mimeType: string
        sizeBytes: number
        contentHash: string
        state: string
        extractionOutput: any
        classification: any
        provenance: any
        createdAt: string
        updatedAt: string
    }

    export interface RequestUploadRequest {
        filename: string
        mimeType: string
        contentHash: string
    }

    export interface RequestUploadResponse {
        objectId: string
        uploadUrl: string
        storageKey: string
    }

    export interface SourceConnectorRow {
        id: string
        workspaceId: string
        type: string
        name: string
        syncSchedule: string | null
        status: string
        lastSyncedAt: string | null
        createdAt: string
        updatedAt: string
    }

    export interface SyncRunRow {
        id: string
        connectorId: string
        workspaceId: string
        status: string
        objectsCreated: number
        objectsUpdated: number
        objectsSkipped: number
        error: string | null
        deltaToken: string | null
        startedAt: string
        completedAt: string | null
    }

    export interface TransitionStateRequest {
        targetState: string
        extractionOutput?: { [key: string]: any }
        classification?: string[]
    }

    export interface UpdateConnectorRequest {
        name?: string
        config?: { [key: string]: any }
        syncSchedule?: string | null
        status?: string
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.bindToProject = this.bindToProject.bind(this)
            this.confirmUpload = this.confirmUpload.bind(this)
            this.createConnector = this.createConnector.bind(this)
            this.deleteConnector = this.deleteConnector.bind(this)
            this.deleteKnowledgeObject = this.deleteKnowledgeObject.bind(this)
            this.getConnector = this.getConnector.bind(this)
            this.getDownloadUrl = this.getDownloadUrl.bind(this)
            this.getKnowledgeObject = this.getKnowledgeObject.bind(this)
            this.listBindings = this.listBindings.bind(this)
            this.listConnectors = this.listConnectors.bind(this)
            this.listKnowledgeObjects = this.listKnowledgeObjects.bind(this)
            this.listSyncRuns = this.listSyncRuns.bind(this)
            this.requestUpload = this.requestUpload.bind(this)
            this.testConnectorConnection = this.testConnectorConnection.bind(this)
            this.transitionState = this.transitionState.bind(this)
            this.triggerSync = this.triggerSync.bind(this)
            this.unbindFromProject = this.unbindFromProject.bind(this)
            this.updateConnector = this.updateConnector.bind(this)
        }

        public async bindToProject(projectId: string, params: BindRequest): Promise<{
    bindings: DocumentBindingRow[]
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/api/knowledge/bindings/${encodeURIComponent(projectId)}`, JSON.stringify(params))
            return await resp.json() as {
    bindings: DocumentBindingRow[]
}
        }

        public async confirmUpload(id: string): Promise<{
    object: KnowledgeObjectRow
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/api/knowledge/objects/${encodeURIComponent(id)}/confirm`)
            return await resp.json() as {
    object: KnowledgeObjectRow
}
        }

        public async createConnector(params: CreateConnectorRequest): Promise<{
    connector: SourceConnectorRow
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/api/knowledge/connectors`, JSON.stringify(params))
            return await resp.json() as {
    connector: SourceConnectorRow
}
        }

        public async deleteConnector(id: string): Promise<{
    deleted: boolean
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("DELETE", `/api/knowledge/connectors/${encodeURIComponent(id)}`)
            return await resp.json() as {
    deleted: boolean
}
        }

        public async deleteKnowledgeObject(id: string): Promise<{
    deleted: boolean
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("DELETE", `/api/knowledge/objects/${encodeURIComponent(id)}`)
            return await resp.json() as {
    deleted: boolean
}
        }

        public async getConnector(id: string): Promise<{
    connector: SourceConnectorRow
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/api/knowledge/connectors/${encodeURIComponent(id)}`)
            return await resp.json() as {
    connector: SourceConnectorRow
}
        }

        public async getDownloadUrl(id: string): Promise<{
    downloadUrl: string
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/api/knowledge/objects/${encodeURIComponent(id)}/download`)
            return await resp.json() as {
    downloadUrl: string
}
        }

        public async getKnowledgeObject(id: string): Promise<{
    object: KnowledgeObjectRow
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/api/knowledge/objects/${encodeURIComponent(id)}`)
            return await resp.json() as {
    object: KnowledgeObjectRow
}
        }

        public async listBindings(projectId: string): Promise<{
    bindings: DocumentBindingRow[]
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/api/knowledge/bindings/${encodeURIComponent(projectId)}`)
            return await resp.json() as {
    bindings: DocumentBindingRow[]
}
        }

        public async listConnectors(): Promise<{
    connectors: SourceConnectorRow[]
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/api/knowledge/connectors`)
            return await resp.json() as {
    connectors: SourceConnectorRow[]
}
        }

        public async listKnowledgeObjects(params: {
    state?: string
}): Promise<{
    objects: KnowledgeObjectRow[]
}> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                state: params.state,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/api/knowledge/objects`, undefined, {query})
            return await resp.json() as {
    objects: KnowledgeObjectRow[]
}
        }

        public async listSyncRuns(id: string): Promise<{
    runs: SyncRunRow[]
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/api/knowledge/connectors/${encodeURIComponent(id)}/sync-runs`)
            return await resp.json() as {
    runs: SyncRunRow[]
}
        }

        public async requestUpload(params: RequestUploadRequest): Promise<RequestUploadResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/api/knowledge/upload`, JSON.stringify(params))
            return await resp.json() as RequestUploadResponse
        }

        public async testConnectorConnection(id: string): Promise<{
    success: boolean
    error?: string
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/api/knowledge/connectors/${encodeURIComponent(id)}/test`)
            return await resp.json() as {
    success: boolean
    error?: string
}
        }

        public async transitionState(id: string, params: TransitionStateRequest): Promise<{
    object: KnowledgeObjectRow
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/api/knowledge/objects/${encodeURIComponent(id)}/transition`, JSON.stringify(params))
            return await resp.json() as {
    object: KnowledgeObjectRow
}
        }

        public async triggerSync(id: string): Promise<{
    syncRunId: string
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/api/knowledge/connectors/${encodeURIComponent(id)}/sync`)
            return await resp.json() as {
    syncRunId: string
}
        }

        public async unbindFromProject(projectId: string, knowledgeObjectId: string): Promise<{
    deleted: boolean
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("DELETE", `/api/knowledge/bindings/${encodeURIComponent(projectId)}/${encodeURIComponent(knowledgeObjectId)}`)
            return await resp.json() as {
    deleted: boolean
}
        }

        public async updateConnector(id: string, params: UpdateConnectorRequest): Promise<{
    connector: SourceConnectorRow
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("PATCH", `/api/knowledge/connectors/${encodeURIComponent(id)}`, JSON.stringify(params))
            return await resp.json() as {
    connector: SourceConnectorRow
}
        }
    }
}

/**
 * The monitor service ping sites and stores the results in the database.
 */
export namespace monitor {
    export interface PingResponse {
        up: boolean
    }

    /**
     * SiteStatus describes the current status of a site and when it was last checked.
     */
    export interface SiteStatus {
        id: number
        up: boolean
        checkedAt: string
    }

    /**
     * StatusResponse is the response type from the Status endpoint.
     */
    export interface StatusResponse {
        /**
         * Sites contains the current status of all sites,
         * keyed by the site ID.
         */
        sites: SiteStatus[]
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.check = this.check.bind(this)
            this.checkAll = this.checkAll.bind(this)
            this.ping = this.ping.bind(this)
            this.status = this.status.bind(this)
        }

        /**
         * Check checks a single site.
         */
        public async check(siteID: number): Promise<{
    up: boolean
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/check/${encodeURIComponent(siteID)}`)
            return await resp.json() as {
    up: boolean
}
        }

        /**
         * CheckAll checks all sites.
         */
        public async checkAll(): Promise<void> {
            await this.baseClient.callTypedAPI("POST", `/check-all`)
        }

        /**
         * Ping pings a specific site and determines whether it's up or down right now.
         */
        public async ping(url: string): Promise<PingResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/ping/${encodeURIComponent(url)}`)
            return await resp.json() as PingResponse
        }

        /**
         * status checks the current up/down status of all monitored sites.
         */
        public async status(): Promise<StatusResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/status`)
            return await resp.json() as StatusResponse
        }
    }
}

export namespace policy {
    export interface PolicyBundleRequest {
        authorization: string
    }

    export interface PolicyBundleResponse {
        constitution: any[]
        shards: { [key: string]: any[] }
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.getPolicyBundle = this.getPolicyBundle.bind(this)
        }

        /**
         * Seam A: Serve compiled policy bundles to OPC axiomregent.
         * GET /api/policy-bundle/:workspaceId — M2M bearer token auth (OIDC JWT or static fallback).
         */
        public async getPolicyBundle(workspaceId: string, params: PolicyBundleRequest): Promise<PolicyBundleResponse> {
            // Convert our params into the objects we need for the request
            const headers = makeRecord<string, string>({
                authorization: params.authorization,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/api/policy-bundle/${encodeURIComponent(workspaceId)}`, undefined, {headers})
            return await resp.json() as PolicyBundleResponse
        }
    }
}

export namespace projects {
    export interface AddRepoRequest {
        githubOrg: string
        repoName: string
        defaultBranch?: string
        isPrimary?: boolean
    }

    export interface CreateEnvironmentRequest {
        name: string
        kind?: "preview" | "development" | "staging" | "production"
        autoDeployBranch?: string
        requiresApproval?: boolean
    }

    export interface CreateProjectRequest {
        name: string
        slug: string
        description?: string
    }

    export interface EnvironmentRow {
        id: string
        projectId: string
        name: string
        kind: "preview" | "development" | "staging" | "production"
        k8sNamespace: string | null
        autoDeployBranch: string | null
        requiresApproval: boolean
        createdAt: string
        updatedAt: string
    }

    export interface MemberRow {
        id: string
        projectId: string
        userId: string
        role: "viewer" | "developer" | "deployer" | "admin"
        createdAt: string
        updatedAt: string
    }

    export interface OrgRow {
        id: string
        name: string
        slug: string
        createdBy: string | null
        createdAt: string
        updatedAt: string
    }

    export interface ProjectRow {
        id: string
        orgId: string
        workspaceId: string
        name: string
        slug: string
        description: string
        createdBy: string | null
        createdAt: string
        updatedAt: string
    }

    export interface RepoRow {
        id: string
        projectId: string
        githubOrg: string
        repoName: string
        defaultBranch: string
        isPrimary: boolean
        githubInstallId: number | null
        createdAt: string
        updatedAt: string
    }

    export interface SetMemberRequest {
        userId: string
        role: "viewer" | "developer" | "deployer" | "admin"
    }

    export interface UpdateProjectRequest {
        name?: string
        description?: string
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.addProjectRepo = this.addProjectRepo.bind(this)
            this.createEnvironment = this.createEnvironment.bind(this)
            this.createProject = this.createProject.bind(this)
            this.deleteEnvironment = this.deleteEnvironment.bind(this)
            this.deleteProject = this.deleteProject.bind(this)
            this.getOrg = this.getOrg.bind(this)
            this.getProject = this.getProject.bind(this)
            this.listEnvironments = this.listEnvironments.bind(this)
            this.listProjectMembers = this.listProjectMembers.bind(this)
            this.listProjectRepos = this.listProjectRepos.bind(this)
            this.listProjects = this.listProjects.bind(this)
            this.removeProjectMember = this.removeProjectMember.bind(this)
            this.removeProjectRepo = this.removeProjectRepo.bind(this)
            this.setProjectMember = this.setProjectMember.bind(this)
            this.updateProject = this.updateProject.bind(this)
        }

        public async addProjectRepo(projectId: string, params: AddRepoRequest): Promise<{
    repo: RepoRow
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/api/projects/${encodeURIComponent(projectId)}/repos`, JSON.stringify(params))
            return await resp.json() as {
    repo: RepoRow
}
        }

        public async createEnvironment(projectId: string, params: CreateEnvironmentRequest): Promise<{
    environment: EnvironmentRow
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/api/projects/${encodeURIComponent(projectId)}/envs`, JSON.stringify(params))
            return await resp.json() as {
    environment: EnvironmentRow
}
        }

        public async createProject(params: CreateProjectRequest): Promise<{
    project: ProjectRow
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/api/projects`, JSON.stringify(params))
            return await resp.json() as {
    project: ProjectRow
}
        }

        public async deleteEnvironment(projectId: string, id: string): Promise<{
    ok: true
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("DELETE", `/api/projects/${encodeURIComponent(projectId)}/envs/${encodeURIComponent(id)}`)
            return await resp.json() as {
    ok: true
}
        }

        public async deleteProject(id: string): Promise<{
    ok: true
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("DELETE", `/api/projects/${encodeURIComponent(id)}`)
            return await resp.json() as {
    ok: true
}
        }

        public async getOrg(): Promise<{
    org: OrgRow
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/api/orgs/current`)
            return await resp.json() as {
    org: OrgRow
}
        }

        public async getProject(id: string): Promise<{
    project: ProjectRow
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/api/projects/${encodeURIComponent(id)}`)
            return await resp.json() as {
    project: ProjectRow
}
        }

        public async listEnvironments(projectId: string): Promise<{
    environments: EnvironmentRow[]
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/api/projects/${encodeURIComponent(projectId)}/envs`)
            return await resp.json() as {
    environments: EnvironmentRow[]
}
        }

        public async listProjectMembers(projectId: string): Promise<{
    members: MemberRow[]
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/api/projects/${encodeURIComponent(projectId)}/members`)
            return await resp.json() as {
    members: MemberRow[]
}
        }

        public async listProjectRepos(projectId: string): Promise<{
    repos: RepoRow[]
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/api/projects/${encodeURIComponent(projectId)}/repos`)
            return await resp.json() as {
    repos: RepoRow[]
}
        }

        public async listProjects(): Promise<{
    projects: ProjectRow[]
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/api/projects`)
            return await resp.json() as {
    projects: ProjectRow[]
}
        }

        public async removeProjectMember(projectId: string, userId: string): Promise<{
    ok: true
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("DELETE", `/api/projects/${encodeURIComponent(projectId)}/members/${encodeURIComponent(userId)}`)
            return await resp.json() as {
    ok: true
}
        }

        public async removeProjectRepo(projectId: string, id: string): Promise<{
    ok: true
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("DELETE", `/api/projects/${encodeURIComponent(projectId)}/repos/${encodeURIComponent(id)}`)
            return await resp.json() as {
    ok: true
}
        }

        public async setProjectMember(projectId: string, params: SetMemberRequest): Promise<{
    member: MemberRow
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/api/projects/${encodeURIComponent(projectId)}/members`, JSON.stringify(params))
            return await resp.json() as {
    member: MemberRow
}
        }

        public async updateProject(id: string, params: UpdateProjectRequest): Promise<{
    project: ProjectRow
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("PUT", `/api/projects/${encodeURIComponent(id)}`, JSON.stringify(params))
            return await resp.json() as {
    project: ProjectRow
}
        }
    }
}

/**
 * The site service is used to store the sites that are being monitored.
 */
export namespace site {
    /**
     * AddParams are the parameters for adding a site to be monitored.
     */
    export interface AddParams {
        /**
         * URL is the URL of the site. If it doesn't contain a scheme
         * (like "http:" or "https:") it defaults to "https:".
         */
        url: string
    }

    export interface ListResponse {
        sites: Site[]
    }

    /**
     * Site describes a monitored site.
     */
    export interface Site {
        id: number
        url: string
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.add = this.add.bind(this)
            this.del = this.del.bind(this)
            this.get = this.get.bind(this)
            this.list = this.list.bind(this)
        }

        /**
         * Add a new site to the list of monitored websites.
         */
        public async add(params: AddParams): Promise<Site> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/site`, JSON.stringify(params))
            return await resp.json() as Site
        }

        /**
         * Delete a site by id.
         */
        public async del(id: number): Promise<void> {
            await this.baseClient.callTypedAPI("DELETE", `/site/${encodeURIComponent(id)}`)
        }

        /**
         * Get a site by id.
         */
        public async get(id: number): Promise<Site> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/site/${encodeURIComponent(id)}`)
            return await resp.json() as Site
        }

        /**
         * Lists the monitored websites.
         */
        public async list(): Promise<ListResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/site`)
            return await resp.json() as ListResponse
        }
    }
}

export namespace sync {
    /**
     * Events pushed from OPC to Stagecraft.
     */
    export interface OpcInboundEvent {
        type: string
        workspaceId: string
        projectId: string
        timestamp: string
        payload: { [key: string]: any }
    }

    /**
     * Events pushed from Stagecraft to connected clients (web UI, OPC).
     */
    export interface SyncEvent {
        type: string
        workspaceId: string
        timestamp: string
        payload: { [key: string]: any }
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.ingestOpcEvent = this.ingestOpcEvent.bind(this)
            this.workspaceEventStream = this.workspaceEventStream.bind(this)
        }

        public async ingestOpcEvent(params: OpcInboundEvent): Promise<{
    accepted: boolean
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/api/sync/opc-events`, JSON.stringify(params))
            return await resp.json() as {
    accepted: boolean
}
        }

        public async workspaceEventStream(): Promise<StreamIn<SyncEvent>> {
            return await this.baseClient.createStreamIn(`/api/sync/events`)
        }
    }
}

export namespace workspaces {
    export interface CreateWorkspaceRequest {
        name: string
        slug: string
    }

    export interface UpdateWorkspaceRequest {
        name?: string
    }

    export interface WorkspaceRow {
        id: string
        orgId: string
        name: string
        slug: string
        objectStoreBucket: string
        createdAt: string
        updatedAt: string
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.createWorkspace = this.createWorkspace.bind(this)
            this.getDefaultWorkspace = this.getDefaultWorkspace.bind(this)
            this.getWorkspace = this.getWorkspace.bind(this)
            this.listWorkspaces = this.listWorkspaces.bind(this)
            this.updateWorkspace = this.updateWorkspace.bind(this)
        }

        public async createWorkspace(params: CreateWorkspaceRequest): Promise<{
    workspace: WorkspaceRow
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/api/workspaces`, JSON.stringify(params))
            return await resp.json() as {
    workspace: WorkspaceRow
}
        }

        public async getDefaultWorkspace(): Promise<{
    workspace: WorkspaceRow
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/api/workspaces/by-org/default`)
            return await resp.json() as {
    workspace: WorkspaceRow
}
        }

        public async getWorkspace(id: string): Promise<{
    workspace: WorkspaceRow
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/api/workspaces/${encodeURIComponent(id)}`)
            return await resp.json() as {
    workspace: WorkspaceRow
}
        }

        public async listWorkspaces(): Promise<{
    workspaces: WorkspaceRow[]
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/api/workspaces`)
            return await resp.json() as {
    workspaces: WorkspaceRow[]
}
        }

        public async updateWorkspace(id: string, params: UpdateWorkspaceRequest): Promise<{
    workspace: WorkspaceRow
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("PUT", `/api/workspaces/${encodeURIComponent(id)}`, JSON.stringify(params))
            return await resp.json() as {
    workspace: WorkspaceRow
}
        }
    }
}

/**
 * The frontend service is the root of the frontend application.
 */
export namespace frontend {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.assets = this.assets.bind(this)
            this.reactrouter = this.reactrouter.bind(this)
        }

        /**
         * Serve all files in the ./assets directory under the /public path prefix.
         */
        public async assets(path: string[]): Promise<void> {
            await this.baseClient.callTypedAPI("HEAD", `/assets/${path.map(encodeURIComponent).join("/")}`)
        }

        public async reactrouter(method: "GET" | "POST" | "PATCH" | "PUT" | "DELETE" | "HEAD" | "OPTIONS" | "TRACE", rest: string[], body?: RequestInit["body"], options?: CallParameters): Promise<globalThis.Response> {
            return this.baseClient.callAPI(method, `/${rest.map(encodeURIComponent).join("/")}`, body, options)
        }
    }
}



function encodeQuery(parts: Record<string, string | string[]>): string {
    const pairs: string[] = []
    for (const key in parts) {
        const val = (Array.isArray(parts[key]) ?  parts[key] : [parts[key]]) as string[]
        for (const v of val) {
            pairs.push(`${key}=${encodeURIComponent(v)}`)
        }
    }
    return pairs.join("&")
}

// makeRecord takes a record and strips any undefined values from it,
// and returns the same record with a narrower type.
// @ts-ignore - TS ignore because makeRecord is not always used
function makeRecord<K extends string | number | symbol, V>(record: Record<K, V | undefined>): Record<K, V> {
    for (const key in record) {
        if (record[key] === undefined) {
            delete record[key]
        }
    }
    return record as Record<K, V>
}

function encodeWebSocketHeaders(headers: Record<string, string>) {
    // url safe, no pad
    const base64encoded = btoa(JSON.stringify(headers))
      .replaceAll("=", "")
      .replaceAll("+", "-")
      .replaceAll("/", "_");
    return "encore.dev.headers." + base64encoded;
}

class WebSocketConnection {
    public ws: WebSocket;

    private hasUpdateHandlers: (() => void)[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        let protocols = ["encore-ws"];
        if (headers) {
            protocols.push(encodeWebSocketHeaders(headers))
        }

        this.ws = new WebSocket(url, protocols)

        this.on("error", () => {
            this.resolveHasUpdateHandlers();
        });

        this.on("close", () => {
            this.resolveHasUpdateHandlers();
        });
    }

    resolveHasUpdateHandlers() {
        const handlers = this.hasUpdateHandlers;
        this.hasUpdateHandlers = [];

        for (const handler of handlers) {
            handler()
        }
    }

    async hasUpdate() {
        // await until a new message have been received, or the socket is closed
        await new Promise((resolve) => {
            this.hasUpdateHandlers.push(() => resolve(null))
        });
    }

    on(type: "error" | "close" | "message" | "open", handler: (event: any) => void) {
        this.ws.addEventListener(type, handler);
    }

    off(type: "error" | "close" | "message" | "open", handler: (event: any) => void) {
        this.ws.removeEventListener(type, handler);
    }

    close() {
        this.ws.close();
    }
}

export class StreamInOut<Request, Response> {
    public socket: WebSocketConnection;
    private buffer: Response[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            this.buffer.push(JSON.parse(event.data));
            this.socket.resolveHasUpdateHandlers();
        });
    }

    close() {
        this.socket.close();
    }

    async send(msg: Request) {
        if (this.socket.ws.readyState === WebSocket.CONNECTING) {
            // await that the socket is opened
            await new Promise((resolve) => {
                this.socket.ws.addEventListener("open", resolve, { once: true });
            });
        }

        return this.socket.ws.send(JSON.stringify(msg));
    }

    async next(): Promise<Response | undefined> {
        for await (const next of this) return next;
        return undefined;
    }

    async *[Symbol.asyncIterator](): AsyncGenerator<Response, undefined, void> {
        while (true) {
            if (this.buffer.length > 0) {
                yield this.buffer.shift() as Response;
            } else {
                if (this.socket.ws.readyState === WebSocket.CLOSED) return;
                await this.socket.hasUpdate();
            }
        }
    }
}

export class StreamIn<Response> {
    public socket: WebSocketConnection;
    private buffer: Response[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            this.buffer.push(JSON.parse(event.data));
            this.socket.resolveHasUpdateHandlers();
        });
    }

    close() {
        this.socket.close();
    }

    async next(): Promise<Response | undefined> {
        for await (const next of this) return next;
        return undefined;
    }

    async *[Symbol.asyncIterator](): AsyncGenerator<Response, undefined, void> {
        while (true) {
            if (this.buffer.length > 0) {
                yield this.buffer.shift() as Response;
            } else {
                if (this.socket.ws.readyState === WebSocket.CLOSED) return;
                await this.socket.hasUpdate();
            }
        }
    }
}

export class StreamOut<Request, Response> {
    public socket: WebSocketConnection;
    private responseValue: Promise<Response>;

    constructor(url: string, headers?: Record<string, string>) {
        let responseResolver: (_: any) => void;
        this.responseValue = new Promise((resolve) => responseResolver = resolve);

        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            responseResolver(JSON.parse(event.data))
        });
    }

    async response(): Promise<Response> {
        return this.responseValue;
    }

    close() {
        this.socket.close();
    }

    async send(msg: Request) {
        if (this.socket.ws.readyState === WebSocket.CONNECTING) {
            // await that the socket is opened
            await new Promise((resolve) => {
                this.socket.ws.addEventListener("open", resolve, { once: true });
            });
        }

        return this.socket.ws.send(JSON.stringify(msg));
    }
}
// CallParameters is the type of the parameters to a method call, but require headers to be a Record type
type CallParameters = Omit<RequestInit, "method" | "body" | "headers"> & {
    /** Headers to be sent with the request */
    headers?: Record<string, string>

    /** Query parameters to be sent with the request */
    query?: Record<string, string | string[]>
}

// AuthDataGenerator is a function that returns a new instance of the authentication data required by this API
export type AuthDataGenerator = () =>
  | auth.AuthParams
  | Promise<auth.AuthParams | undefined>
  | undefined;

// A fetcher is the prototype for the inbuilt Fetch function
export type Fetcher = typeof fetch;

const boundFetch = fetch.bind(this);

class BaseClient {
    readonly baseURL: string
    readonly fetcher: Fetcher
    readonly headers: Record<string, string>
    readonly requestInit: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }
    readonly authGenerator?: AuthDataGenerator

    constructor(baseURL: string, options: ClientOptions) {
        this.baseURL = baseURL
        this.headers = {}

        // Add User-Agent header if the script is running in the server
        // because browsers do not allow setting User-Agent headers to requests
        if (!BROWSER) {
            this.headers["User-Agent"] = "fullstack-app-37a2-Generated-TS-Client (Encore/v1.56.5)";
        }

        this.requestInit = options.requestInit ?? {};

        // Setup what fetch function we'll be using in the base client
        if (options.fetcher !== undefined) {
            this.fetcher = options.fetcher
        } else {
            this.fetcher = boundFetch
        }

        // Setup an authentication data generator using the auth data token option
        if (options.auth !== undefined) {
            const auth = options.auth
            if (typeof auth === "function") {
                this.authGenerator = auth
            } else {
                this.authGenerator = () => auth
            }
        }
    }

    async getAuthData(): Promise<CallParameters | undefined> {
        let authData: auth.AuthParams | undefined;

        // If authorization data generator is present, call it and add the returned data to the request
        if (this.authGenerator) {
            const mayBePromise = this.authGenerator();
            if (mayBePromise instanceof Promise) {
                authData = await mayBePromise;
            } else {
                authData = mayBePromise;
            }
        }

        if (authData) {
            const data: CallParameters = {};

            data.headers = makeRecord<string, string>({
                authorization: authData.authorization,
                cookie:        authData.cookie,
            });

            return data;
        }

        return undefined;
    }

    // createStreamInOut sets up a stream to a streaming API endpoint.
    async createStreamInOut<Request, Response>(path: string, params?: CallParameters): Promise<StreamInOut<Request, Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamInOut(this.baseURL + path + queryString, headers);
    }

    // createStreamIn sets up a stream to a streaming API endpoint.
    async createStreamIn<Response>(path: string, params?: CallParameters): Promise<StreamIn<Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamIn(this.baseURL + path + queryString, headers);
    }

    // createStreamOut sets up a stream to a streaming API endpoint.
    async createStreamOut<Request, Response>(path: string, params?: CallParameters): Promise<StreamOut<Request, Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamOut(this.baseURL + path + queryString, headers);
    }

    // callTypedAPI makes an API call, defaulting content type to "application/json"
    public async callTypedAPI(method: string, path: string, body?: RequestInit["body"], params?: CallParameters): Promise<Response> {
        return this.callAPI(method, path, body, {
            ...params,
            headers: { "Content-Type": "application/json", ...params?.headers }
        });
    }

    // callAPI is used by each generated API method to actually make the request
    public async callAPI(method: string, path: string, body?: RequestInit["body"], params?: CallParameters): Promise<Response> {
        let { query, headers, ...rest } = params ?? {}
        const init = {
            ...this.requestInit,
            ...rest,
            method,
            body: body ?? null,
        }

        // Merge our headers with any predefined headers
        init.headers = {...this.headers, ...init.headers, ...headers}

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                init.headers = {...init.headers, ...authData.headers};
            }
        }

        // Make the actual request
        const queryString = query ? '?' + encodeQuery(query) : ''
        const response = await this.fetcher(this.baseURL+path+queryString, init)

        // handle any error responses
        if (!response.ok) {
            // try and get the error message from the response body
            let body: APIErrorResponse = { code: ErrCode.Unknown, message: `request failed: status ${response.status}` }

            // if we can get the structured error we should, otherwise give a best effort
            try {
                const text = await response.text()

                try {
                    const jsonBody = JSON.parse(text)
                    if (isAPIErrorResponse(jsonBody)) {
                        body = jsonBody
                    } else {
                        body.message += ": " + JSON.stringify(jsonBody)
                    }
                } catch {
                    body.message += ": " + text
                }
            } catch (e) {
                // otherwise we just append the text to the error message
                body.message += ": " + String(e)
            }

            throw new APIError(response.status, body)
        }

        return response
    }
}

/**
 * APIErrorDetails represents the response from an Encore API in the case of an error
 */
interface APIErrorResponse {
    code: ErrCode
    message: string
    details?: any
}

function isAPIErrorResponse(err: any): err is APIErrorResponse {
    return (
        err !== undefined && err !== null &&
        isErrCode(err.code) &&
        typeof(err.message) === "string" &&
        (err.details === undefined || err.details === null || typeof(err.details) === "object")
    )
}

function isErrCode(code: any): code is ErrCode {
    return code !== undefined && Object.values(ErrCode).includes(code)
}

/**
 * APIError represents a structured error as returned from an Encore application.
 */
export class APIError extends Error {
    /**
     * The HTTP status code associated with the error.
     */
    public readonly status: number

    /**
     * The Encore error code
     */
    public readonly code: ErrCode

    /**
     * The error details
     */
    public readonly details?: any

    constructor(status: number, response: APIErrorResponse) {
        // extending errors causes issues after you construct them, unless you apply the following fixes
        super(response.message);

        // set error name as constructor name, make it not enumerable to keep native Error behavior
        // https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/new.target#new.target_in_constructors
        Object.defineProperty(this, 'name', {
            value:        'APIError',
            enumerable:   false,
            configurable: true,
        })

        // fix the prototype chain
        if ((Object as any).setPrototypeOf == undefined) {
            (this as any).__proto__ = APIError.prototype
        } else {
            Object.setPrototypeOf(this, APIError.prototype);
        }

        // capture a stack trace
        if ((Error as any).captureStackTrace !== undefined) {
            (Error as any).captureStackTrace(this, this.constructor);
        }

        this.status = status
        this.code = response.code
        this.details = response.details
    }
}

/**
 * Typeguard allowing use of an APIError's fields'
 */
export function isAPIError(err: any): err is APIError {
    return err instanceof APIError;
}

export enum ErrCode {
    /**
     * OK indicates the operation was successful.
     */
    OK = "ok",

    /**
     * Canceled indicates the operation was canceled (typically by the caller).
     *
     * Encore will generate this error code when cancellation is requested.
     */
    Canceled = "canceled",

    /**
     * Unknown error. An example of where this error may be returned is
     * if a Status value received from another address space belongs to
     * an error-space that is not known in this address space. Also
     * errors raised by APIs that do not return enough error information
     * may be converted to this error.
     *
     * Encore will generate this error code in the above two mentioned cases.
     */
    Unknown = "unknown",

    /**
     * InvalidArgument indicates client specified an invalid argument.
     * Note that this differs from FailedPrecondition. It indicates arguments
     * that are problematic regardless of the state of the system
     * (e.g., a malformed file name).
     *
     * This error code will not be generated by the gRPC framework.
     */
    InvalidArgument = "invalid_argument",

    /**
     * DeadlineExceeded means operation expired before completion.
     * For operations that change the state of the system, this error may be
     * returned even if the operation has completed successfully. For
     * example, a successful response from a server could have been delayed
     * long enough for the deadline to expire.
     *
     * The gRPC framework will generate this error code when the deadline is
     * exceeded.
     */
    DeadlineExceeded = "deadline_exceeded",

    /**
     * NotFound means some requested entity (e.g., file or directory) was
     * not found.
     *
     * This error code will not be generated by the gRPC framework.
     */
    NotFound = "not_found",

    /**
     * AlreadyExists means an attempt to create an entity failed because one
     * already exists.
     *
     * This error code will not be generated by the gRPC framework.
     */
    AlreadyExists = "already_exists",

    /**
     * PermissionDenied indicates the caller does not have permission to
     * execute the specified operation. It must not be used for rejections
     * caused by exhausting some resource (use ResourceExhausted
     * instead for those errors). It must not be
     * used if the caller cannot be identified (use Unauthenticated
     * instead for those errors).
     *
     * This error code will not be generated by the gRPC core framework,
     * but expect authentication middleware to use it.
     */
    PermissionDenied = "permission_denied",

    /**
     * ResourceExhausted indicates some resource has been exhausted, perhaps
     * a per-user quota, or perhaps the entire file system is out of space.
     *
     * This error code will be generated by the gRPC framework in
     * out-of-memory and server overload situations, or when a message is
     * larger than the configured maximum size.
     */
    ResourceExhausted = "resource_exhausted",

    /**
     * FailedPrecondition indicates operation was rejected because the
     * system is not in a state required for the operation's execution.
     * For example, directory to be deleted may be non-empty, an rmdir
     * operation is applied to a non-directory, etc.
     *
     * A litmus test that may help a service implementor in deciding
     * between FailedPrecondition, Aborted, and Unavailable:
     *  (a) Use Unavailable if the client can retry just the failing call.
     *  (b) Use Aborted if the client should retry at a higher-level
     *      (e.g., restarting a read-modify-write sequence).
     *  (c) Use FailedPrecondition if the client should not retry until
     *      the system state has been explicitly fixed. E.g., if an "rmdir"
     *      fails because the directory is non-empty, FailedPrecondition
     *      should be returned since the client should not retry unless
     *      they have first fixed up the directory by deleting files from it.
     *  (d) Use FailedPrecondition if the client performs conditional
     *      REST Get/Update/Delete on a resource and the resource on the
     *      server does not match the condition. E.g., conflicting
     *      read-modify-write on the same resource.
     *
     * This error code will not be generated by the gRPC framework.
     */
    FailedPrecondition = "failed_precondition",

    /**
     * Aborted indicates the operation was aborted, typically due to a
     * concurrency issue like sequencer check failures, transaction aborts,
     * etc.
     *
     * See litmus test above for deciding between FailedPrecondition,
     * Aborted, and Unavailable.
     */
    Aborted = "aborted",

    /**
     * OutOfRange means operation was attempted past the valid range.
     * E.g., seeking or reading past end of file.
     *
     * Unlike InvalidArgument, this error indicates a problem that may
     * be fixed if the system state changes. For example, a 32-bit file
     * system will generate InvalidArgument if asked to read at an
     * offset that is not in the range [0,2^32-1], but it will generate
     * OutOfRange if asked to read from an offset past the current
     * file size.
     *
     * There is a fair bit of overlap between FailedPrecondition and
     * OutOfRange. We recommend using OutOfRange (the more specific
     * error) when it applies so that callers who are iterating through
     * a space can easily look for an OutOfRange error to detect when
     * they are done.
     *
     * This error code will not be generated by the gRPC framework.
     */
    OutOfRange = "out_of_range",

    /**
     * Unimplemented indicates operation is not implemented or not
     * supported/enabled in this service.
     *
     * This error code will be generated by the gRPC framework. Most
     * commonly, you will see this error code when a method implementation
     * is missing on the server. It can also be generated for unknown
     * compression algorithms or a disagreement as to whether an RPC should
     * be streaming.
     */
    Unimplemented = "unimplemented",

    /**
     * Internal errors. Means some invariants expected by underlying
     * system has been broken. If you see one of these errors,
     * something is very broken.
     *
     * This error code will be generated by the gRPC framework in several
     * internal error conditions.
     */
    Internal = "internal",

    /**
     * Unavailable indicates the service is currently unavailable.
     * This is a most likely a transient condition and may be corrected
     * by retrying with a backoff. Note that it is not always safe to retry
     * non-idempotent operations.
     *
     * See litmus test above for deciding between FailedPrecondition,
     * Aborted, and Unavailable.
     *
     * This error code will be generated by the gRPC framework during
     * abrupt shutdown of a server process or network connection.
     */
    Unavailable = "unavailable",

    /**
     * DataLoss indicates unrecoverable data loss or corruption.
     *
     * This error code will not be generated by the gRPC framework.
     */
    DataLoss = "data_loss",

    /**
     * Unauthenticated indicates the request does not have valid
     * authentication credentials for the operation.
     *
     * The gRPC framework will generate this error code when the
     * authentication metadata is invalid or a Credentials callback fails,
     * but also expect authentication middleware to generate it.
     */
    Unauthenticated = "unauthenticated",
}
