apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.workloadIdentity.serviceAccountName }}
  annotations:
    azure.workload.identity/client-id: {{ .Values.workloadIdentity.clientId | quote }}
