//! Markdown renderer — emits CODEBASE-INDEX.md from CodebaseIndex.

use crate::types::CodebaseIndex;

/// Render the index as a human-readable markdown document.
pub fn render_markdown(index: &CodebaseIndex) -> String {
    let mut out = String::new();

    out.push_str("# Codebase Index — Open Agentic Platform\n\n");
    out.push_str(&format!(
        "> Auto-generated by `codebase-indexer` v{}.\n",
        index.build.indexer_version
    ));
    out.push_str(&format!(
        "> Content hash: `{}`\n\n",
        index.build.content_hash
    ));

    // Layer 1: Inventory
    let rust_pkgs: Vec<_> = index
        .inventory
        .iter()
        .filter(|p| matches!(p.kind, crate::types::PackageKind::RustLib | crate::types::PackageKind::RustBin | crate::types::PackageKind::RustLibBin))
        .collect();
    let npm_pkgs: Vec<_> = index
        .inventory
        .iter()
        .filter(|p| matches!(p.kind, crate::types::PackageKind::NpmPackage | crate::types::PackageKind::NpmWorkspace))
        .collect();

    out.push_str(&format!(
        "## Layer 1: Crate & Package Inventory ({} total)\n\n",
        index.inventory.len()
    ));

    if !rust_pkgs.is_empty() {
        out.push_str(&format!("### Rust Crates ({})\n\n", rust_pkgs.len()));
        out.push_str("| Name | Path | Kind | Version | Internal Deps |\n");
        out.push_str("|------|------|------|---------|---------------|\n");
        for p in &rust_pkgs {
            let kind = format!("{:?}", p.kind).to_lowercase().replace("rust", "rust-");
            let version = p.version.as_deref().unwrap_or("-");
            let deps = p
                .internal_deps
                .as_ref()
                .map(|d| d.join(", "))
                .unwrap_or_else(|| "-".into());
            out.push_str(&format!(
                "| {} | `{}` | {} | {} | {} |\n",
                p.name, p.path, kind, version, deps
            ));
        }
        out.push('\n');
    }

    if !npm_pkgs.is_empty() {
        out.push_str(&format!("### NPM Packages ({})\n\n", npm_pkgs.len()));
        out.push_str("| Name | Path | Kind | Version |\n");
        out.push_str("|------|------|------|---------|\n");
        for p in &npm_pkgs {
            let kind = format!("{:?}", p.kind).to_lowercase().replace("npm", "npm-");
            let version = p.version.as_deref().unwrap_or("-");
            out.push_str(&format!(
                "| {} | `{}` | {} | {} |\n",
                p.name, p.path, kind, version
            ));
        }
        out.push('\n');
    }

    // Layer 2: Traceability
    out.push_str("## Layer 2: Spec-to-Code Traceability\n\n");

    if !index.traceability.mappings.is_empty() {
        out.push_str(&format!(
            "### Mapped Specs ({})\n\n",
            index.traceability.mappings.len()
        ));
        out.push_str("| Spec ID | Status | Implementing Paths |\n");
        out.push_str("|---------|--------|--------------------|\n");
        for m in &index.traceability.mappings {
            let status = m.spec_status.as_deref().unwrap_or("-");
            let paths: Vec<String> = m
                .implementing_paths
                .iter()
                .map(|p| format!("`{}`", p.path))
                .collect();
            out.push_str(&format!(
                "| {} | {} | {} |\n",
                m.spec_id,
                status,
                paths.join(", ")
            ));
        }
        out.push('\n');
    }

    if !index.traceability.orphaned_specs.is_empty() {
        out.push_str(&format!(
            "### Orphaned Specs ({})\n\n",
            index.traceability.orphaned_specs.len()
        ));
        for s in &index.traceability.orphaned_specs {
            out.push_str(&format!("- `{s}`\n"));
        }
        out.push('\n');
    }

    if !index.traceability.untraced_code.is_empty() {
        out.push_str(&format!(
            "### Untraced Code ({})\n\n",
            index.traceability.untraced_code.len()
        ));
        for p in &index.traceability.untraced_code {
            out.push_str(&format!("- `{p}`\n"));
        }
        out.push('\n');
    }

    // Layer 3: Factory
    if !index.factory.is_empty() {
        out.push_str(&format!(
            "## Layer 3: Factory Adapters ({})\n\n",
            index.factory.len()
        ));
        out.push_str("| Name | Stack | Language | Runtime | Stages |\n");
        out.push_str("|------|-------|----------|---------|--------|\n");
        for a in &index.factory {
            let stack = a.target_stack.as_deref().unwrap_or("-");
            let lang = a.stack_language.as_deref().unwrap_or("-");
            let runtime = a.stack_runtime.as_deref().unwrap_or("-");
            let stages = a
                .phase_coverage
                .as_ref()
                .map(|s| s.len().to_string())
                .unwrap_or_else(|| "0".into());
            out.push_str(&format!(
                "| {} | {} | {} | {} | {} |\n",
                a.name, stack, lang, runtime, stages
            ));
        }
        out.push('\n');
    }

    // Layer 4: Infrastructure
    out.push_str("## Layer 4: Infrastructure\n\n");

    render_named_section(&mut out, "Tools", &index.infrastructure.tools.iter().map(|t| {
        (&t.name as &str, &t.path as &str)
    }).collect::<Vec<_>>());

    render_named_section(&mut out, "Agents", &index.infrastructure.agents.iter().map(|e| {
        (e.name.as_str(), e.path.as_str())
    }).collect::<Vec<_>>());

    render_named_section(&mut out, "Commands", &index.infrastructure.commands.iter().map(|e| {
        (e.name.as_str(), e.path.as_str())
    }).collect::<Vec<_>>());

    render_named_section(&mut out, "Rules", &index.infrastructure.rules.iter().map(|e| {
        (e.name.as_str(), e.path.as_str())
    }).collect::<Vec<_>>());

    render_named_section(&mut out, "Schemas", &index.infrastructure.schemas.iter().map(|e| {
        (e.name.as_str(), e.path.as_str())
    }).collect::<Vec<_>>());

    // Diagnostics
    let total_diags = index.diagnostics.warnings.len() + index.diagnostics.errors.len();
    if total_diags > 0 {
        out.push_str(&format!("## Diagnostics ({total_diags})\n\n"));

        if !index.diagnostics.errors.is_empty() {
            out.push_str(&format!(
                "### Errors ({})\n\n",
                index.diagnostics.errors.len()
            ));
            for d in &index.diagnostics.errors {
                let path = d.path.as_deref().unwrap_or("");
                out.push_str(&format!("- **{}**: {} {}\n", d.code, d.message, path));
            }
            out.push('\n');
        }

        if !index.diagnostics.warnings.is_empty() {
            out.push_str(&format!(
                "### Warnings ({})\n\n",
                index.diagnostics.warnings.len()
            ));
            for d in &index.diagnostics.warnings {
                let path = d.path.as_deref().unwrap_or("");
                out.push_str(&format!("- **{}**: {} {}\n", d.code, d.message, path));
            }
            out.push('\n');
        }
    }

    out
}

fn render_named_section(out: &mut String, title: &str, items: &[(&str, &str)]) {
    out.push_str(&format!("### {} ({})\n\n", title, items.len()));
    if items.is_empty() {
        out.push_str("_None found._\n\n");
        return;
    }
    for (name, path) in items {
        out.push_str(&format!("- **{name}** — `{path}`\n"));
    }
    out.push('\n');
}
