/**
 * Barrel module for the agent-frontmatter TS mirror (spec 111 §2.1).
 *
 * The sibling `*.ts` files are generated by `ts-rs` from
 * `crates/agent-frontmatter/src/types.rs`. The generator is invoked on every
 * `cargo test` (see `crates/agent-frontmatter/tests/ts_bindings.rs`) and
 * `make ci` runs `git diff --exit-code` afterwards, so drift between the
 * Rust type and the TS mirror is an immediate CI failure.
 *
 * This file is the only hand-maintained entry in this directory. It exists
 * because the Rust `UnifiedFrontmatter` uses `#[serde(flatten)]` to preserve
 * unknown fields (`extra: HashMap<String, serde_json::Value>` — spec 054
 * FR-013) and `ts-rs` cannot express an open index signature on a named
 * struct. `CatalogFrontmatter` re-adds that openness on the wire side so
 * stagecraft can store arbitrary forward-compatible keys in JSONB without
 * the catalog API needing a codegen bump.
 */

import type { UnifiedFrontmatter } from "./UnifiedFrontmatter";

export type { AgentType } from "./AgentType";
export type { GovernanceRequirement } from "./GovernanceRequirement";
export type { HookDeclaration } from "./HookDeclaration";
export type { HookHandlerType } from "./HookHandlerType";
export type { MutationCapability } from "./MutationCapability";
export type { SafetyTier } from "./SafetyTier";
export type { UnifiedFrontmatter } from "./UnifiedFrontmatter";

/**
 * Wire shape stored in `agent_catalog.frontmatter` (JSONB) and carried on
 * `agent.catalog.updated` envelopes. All `UnifiedFrontmatter` fields are
 * preserved with their Rust-side types; extra keys are allowed through an
 * open index signature to round-trip the Rust `extra` flatten map.
 */
export type CatalogFrontmatter = UnifiedFrontmatter & {
  [key: string]: unknown;
};
