// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Structured replacement for the desktop's boolean permission flags.
 *
 * Derivable from `SafetyTier` when absent:
 * - `Tier1` → `ReadOnly`
 * - `Tier2` → `ReadWrite`
 * - `Tier3` → `Full`
 */
export type MutationCapability = "read-only" | "read-write" | "full";
