apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "logto.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "logto.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "logto.name" . }}
    spec:
      initContainers:
        {{- if not .Values.customSetup.enabled }}
        - name: logto-db-seed
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: IfNotPresent
          env:
            - name: DB_URL
              value: "postgres://{{ .Values.postgresql.auth.username }}:{{ .Values.postgresql.auth.password }}@logto-postgresql:5432/{{ .Values.postgresql.auth.database }}"
          command: ["npm", "run", "cli", "db", "seed"]
        {{- end }}
      containers:
        - name: logto
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3001
          env:
            - name: TRUST_PROXY_HEADER
              value: "{{ .Values.logto.trustProxyHeader }}"
            - name: ENDPOINT
              value: "{{ .Values.logto.endpoint }}"
            - name: ADMIN_ENDPOINT
              value: "{{ .Values.logto.adminEndpoint }}"
            - name: DB_URL
              value: "postgres://{{ .Values.postgresql.auth.username }}:{{ .Values.postgresql.auth.password }}@logto-postgresql:5432/{{ .Values.postgresql.auth.database }}"
