apiVersion: v1
kind: Service
metadata:
  name: {{ include "logto.fullname" . }}
spec:
  type: ClusterIP
  selector:
    app: {{ include "logto.name" . }}
  ports:
    - name: http
      port: 3001
      targetPort: 3001
