import { defineConfig } from "vitest/config";
// import tsconfigPaths from "vite-tsconfig-paths";
import path from "path";

// When running under `encore test`, the Encore CLI provides the native
// runtime.  When running bare `vitest` (npm test / CI), we swap in
// lightweight mocks so unit tests can execute without the runtime binary.
const hasEncoreRuntime = !!process.env.ENCORE_RUNTIME_LIB;

export default defineConfig({
  // plugins: [tsconfigPaths()],
  resolve: {
    alias: {
      "~encore": path.resolve(__dirname, "./encore.gen"),
    },
  },
  test: {
    ...(!hasEncoreRuntime && {
      alias: {
        "encore.dev/api": path.resolve(
          __dirname,
          "./test/__mocks__/encore-api.ts",
        ),
        "encore.dev/log": path.resolve(
          __dirname,
          "./test/__mocks__/encore-log.ts",
        ),
        "encore.dev/pubsub": path.resolve(
          __dirname,
          "./test/__mocks__/encore-pubsub.ts",
        ),
        // `~encore/*` normally resolves into `./encore.gen/*`, which is
        // generated by the Encore CLI and git-ignored. CI runs `npm test`
        // without that directory — stub the auth barrel so modules importing
        // `getAuthData` can be loaded at all.
        "~encore/auth": path.resolve(
          __dirname,
          "./test/__mocks__/encore-auth.ts",
        ),
      },
      // Integration tests that require Encore service infrastructure
      // (databases, service-to-service calls) must run via `encore test`.
      exclude: ["**/node_modules/**", "**/dist/**", "**/check.test.ts"],
    }),
  },
});
