// Spec 163 §7 — resolving the project's spec-spine source on disk.
//
// For projects produced by the substrate (spec 167 — born-with kernel),
// the project's `.derived/spec-registry/registry.json` is generated by
// the project's own spec-compiler invocation. Spec 163 reads from there.
// For freshly-imported projects that have not yet run through the
// decomposition pipeline, the registry may be absent — that case
// surfaces as `null` here and the route renders the FR-007 empty-state
// CTA.
//
// The MVP path resolution is environment-driven:
//
//   STAGECRAFT_PROJECT_REGISTRY_BASE=<dir>
//
// when set, the resolver looks under `<dir>/<projectId>/` for a project
// repo root containing `.derived/spec-registry/registry.json` and a
// `specs/` directory. This is a clean fixture seam for tests and a
// natural mount-point for the future per-project registry mirroring
// path spec 167 will populate. When the env var is unset, or the
// expected files are missing, the resolver returns null and the view
// degrades to its empty state per FR-007.

import { access } from "node:fs/promises";
import { join, resolve } from "node:path";

export interface ProjectSpecRoots {
  /** Absolute path to the project repo root (the directory that owns specs/). */
  projectRoot: string;
  /** Absolute path to the registry.json the project's spec-compiler emitted. */
  registryPath: string;
}

export interface ResolverOptions {
  /**
   * Override for STAGECRAFT_PROJECT_REGISTRY_BASE. Tests pass this directly
   * to keep behaviour deterministic regardless of ambient env.
   */
  base?: string | null;
}

/**
 * Resolve `(projectRoot, registryPath)` for a projectId. Returns null
 * when no registry is available — the FR-007 empty-state case.
 *
 * The resolver does NOT consult the projects DB row directly: registry
 * presence is independent of project metadata. A project may exist
 * without a registry (newly imported); a registry may be present on
 * disk before the project row exists (test fixtures). The pairing is
 * established by the directory layout below the configured base.
 */
export async function resolveProjectRegistry(
  projectId: string,
  opts: ResolverOptions = {}
): Promise<ProjectSpecRoots | null> {
  const base = opts.base ?? process.env.STAGECRAFT_PROJECT_REGISTRY_BASE ?? null;
  if (!base) return null;

  const projectRoot = resolve(base, projectId);
  const registryPath = join(projectRoot, ".derived", "spec-registry", "registry.json");

  try {
    await access(registryPath);
  } catch {
    return null;
  }
  return { projectRoot, registryPath };
}
