//! Generic Layer 1 + 2 + Diagnostics markdown renderer.
//!
//! Cut D W-07b moved the full (Layers 1-5) renderer out of the
//! codebase-indexer and into `tools/oap/oap-code-index-enrich/`,
//! leaving the spec-spine binary unable to render anything. Epic 2
//! I11 puts a *generic* renderer back — covering only Layers 1
//! (crate + package inventory), 2 (spec→code traceability), and the
//! Diagnostics tail — so the spec-spine consumer protocol
//! (`codebase-indexer render`) is self-sufficient without pulling
//! the OAP-overlay surface (factory adapters, infrastructure
//! inventory, workflow traceability) back into the generic crate.
//!
//! The OAP overlay binary continues to render its own enriched view
//! independently. Future work (tracked in the discovery appendix) may
//! refactor the OAP overlay to delegate the first three sections via
//! `render_generic` so the byte-identical-prefix contract is
//! mechanically enforced.

use crate::types::{
    CodebaseIndex, Diagnostic, PackageKind, TraceMapping, TraceSource,
};

/// Render the generic Layer 1 + 2 + Diagnostics markdown for an
/// in-memory `CodebaseIndex`. Pure function — produces the same
/// string for any given input across runs.
pub fn render_generic(index: &CodebaseIndex) -> String {
    let mut out = String::new();

    out.push_str("# Codebase Index — Open Agentic Platform (generic view)\n\n");
    out.push_str(&format!(
        "> Auto-generated by `codebase-indexer` v{}.\n",
        index.build.indexer_version
    ));
    out.push_str(&format!(
        "> Content hash: `{}`\n",
        index.build.content_hash
    ));
    out.push_str("> Layers 1-2 + Diagnostics. OAP-overlay Layers 3-5 are emitted by\n");
    out.push_str("> `oap-code-index-enrich render` to `.derived/codebase-index/CODEBASE-INDEX.md`.\n\n");

    render_layer_1(&mut out, index);
    render_layer_2(&mut out, index);
    render_diagnostics(&mut out, index);
    out
}

fn render_layer_1(out: &mut String, index: &CodebaseIndex) {
    let rust_pkgs: Vec<_> = index
        .inventory
        .iter()
        .filter(|p| {
            matches!(
                p.kind,
                PackageKind::RustLib | PackageKind::RustBin | PackageKind::RustLibBin
            )
        })
        .collect();
    let npm_pkgs: Vec<_> = index
        .inventory
        .iter()
        .filter(|p| matches!(p.kind, PackageKind::NpmPackage | PackageKind::NpmWorkspace))
        .collect();

    out.push_str(&format!(
        "## Layer 1: Crate & Package Inventory ({} total)\n\n",
        index.inventory.len()
    ));

    if !rust_pkgs.is_empty() {
        out.push_str(&format!("### Rust Crates ({})\n\n", rust_pkgs.len()));
        out.push_str("| Name | Path | Kind | Version | Spec |\n");
        out.push_str("|------|------|------|---------|------|\n");
        for p in &rust_pkgs {
            let version = p.version.as_deref().unwrap_or("-");
            let spec = p
                .spec_ref
                .as_deref()
                .map(|s| format!("`{s}`"))
                .unwrap_or_else(|| "-".to_string());
            out.push_str(&format!(
                "| {} | `{}` | {} | {} | {} |\n",
                p.name,
                p.path,
                kind_label(&p.kind),
                version,
                spec
            ));
        }
        out.push('\n');
    }

    if !npm_pkgs.is_empty() {
        out.push_str(&format!("### NPM Packages ({})\n\n", npm_pkgs.len()));
        out.push_str("| Name | Path | Kind | Version | Spec |\n");
        out.push_str("|------|------|------|---------|------|\n");
        for p in &npm_pkgs {
            let version = p.version.as_deref().unwrap_or("-");
            let spec = p
                .spec_ref
                .as_deref()
                .map(|s| format!("`{s}`"))
                .unwrap_or_else(|| "-".to_string());
            out.push_str(&format!(
                "| {} | `{}` | {} | {} | {} |\n",
                p.name,
                p.path,
                kind_label(&p.kind),
                version,
                spec
            ));
        }
        out.push('\n');
    }
}

fn render_layer_2(out: &mut String, index: &CodebaseIndex) {
    let mappings = &index.traceability.mappings;
    out.push_str(&format!(
        "## Layer 2: Spec → Code Traceability ({} mapped, {} orphaned specs, {} untraced paths)\n\n",
        mappings.len(),
        index.traceability.orphaned_specs.len(),
        index.traceability.untraced_code.len()
    ));

    let implements_rows: Vec<&TraceMapping> = mappings
        .iter()
        .filter(|m| !m.implementing_paths.is_empty())
        .collect();

    if !implements_rows.is_empty() {
        out.push_str(&format!(
            "### Implements ({} specs claim implementing paths)\n\n",
            implements_rows.len()
        ));
        out.push_str("| Spec | Status | Paths |\n");
        out.push_str("|------|--------|-------|\n");
        for m in &implements_rows {
            let status = m.spec_status.as_deref().unwrap_or("-");
            let paths: Vec<String> = m
                .implementing_paths
                .iter()
                .map(|p| {
                    let source = match &p.source {
                        Some(TraceSource::SpecImplements) => "spec",
                        Some(TraceSource::CargoMetadataCrate) => "cargo-metadata-crate",
                        Some(TraceSource::CargoMetadataModule) => "cargo-metadata-module",
                        Some(TraceSource::CommentHeader) => "comment-header",
                        Some(TraceSource::Multiple) => "multiple",
                        None => "-",
                    };
                    format!("`{}` ({})", p.path, source)
                })
                .collect();
            out.push_str(&format!(
                "| `{}` | {} | {} |\n",
                m.spec_id,
                status,
                paths.join("<br/>")
            ));
        }
        out.push('\n');
    }
}

fn render_diagnostics(out: &mut String, index: &CodebaseIndex) {
    if index.diagnostics.warnings.is_empty() && index.diagnostics.errors.is_empty() {
        return;
    }
    out.push_str("## Diagnostics\n\n");
    if !index.diagnostics.errors.is_empty() {
        out.push_str(&format!(
            "### Errors ({})\n\n",
            index.diagnostics.errors.len()
        ));
        for d in &index.diagnostics.errors {
            push_diag(out, d);
        }
        out.push('\n');
    }
    if !index.diagnostics.warnings.is_empty() {
        out.push_str(&format!(
            "### Warnings ({})\n\n",
            index.diagnostics.warnings.len()
        ));
        for d in &index.diagnostics.warnings {
            push_diag(out, d);
        }
        out.push('\n');
    }
}

fn push_diag(out: &mut String, d: &Diagnostic) {
    let path = d.path.as_deref().unwrap_or("");
    if path.is_empty() {
        out.push_str(&format!("- **{}**: {}\n", d.code, d.message));
    } else {
        out.push_str(&format!("- **{}** `{}`: {}\n", d.code, path, d.message));
    }
}

fn kind_label(k: &PackageKind) -> &'static str {
    match k {
        PackageKind::RustLib => "rust-lib",
        PackageKind::RustBin => "rust-bin",
        PackageKind::RustLibBin => "rust-lib-bin",
        PackageKind::NpmPackage => "npm-package",
        PackageKind::NpmWorkspace => "npm-workspace",
    }
}
